POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name":"Athena Ho",
    "number":"0450199081"
}

###

POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name":"Justin Lu",
    "number":"0468403004"
}

###

POST http://localhost:3001/api/persons
Content-type: application/application/json

{
    "name":"Justin Lu"
}

###

POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name":"Justin Lu",
    "number":"1234"
}

###
DELETE http://localhost:3001/api/persons/1