POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name":"Wiiliam KA",
    "number":"2162"
}

###

POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name":"Justin Lu",
    "number":"1234567890"
}

###

POST http://localhost:3001/api/persons
Content-type: application/application/json

{
    "name":"Justin Lu"
}

###

POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name":"Justin Lu",
    "number":"1234"
}

###
DELETE http://localhost:3001/api/persons/60a054b3d57bf006fc6621ea